### ISSUE TITLE
Feature requests: spacebar pause, applescript integration

### ISSUE THREAD

**Issue by danielgolden** [vitorgalvao/fog#1]
First, this app is awesome. Thanks for doing this and making publicly available. I was using epichrome a very dumbed down overcast mac app, but this is superior. I have 2 ideas for what I think would be awesome updates.

---
1. When the app is foremost/active, being able to press space bar to pause/play.
2. Allowing applescript to hook into this app so that it could control basic playback (play/pause) via applescript. Allowing for something like:

``` applescript
tell application "System Events"
    set MyList to (name of every process)
end tell
if (MyList contains "Fog") is true then
    tell application "Fog" to playpause
end if
```

---

Kudos on shipping this in the first place, it's absolutely awesome.

**Comment by vitorgalvao** [comment]
Thank you for the kind words, Daniel.

As for number **1**, just released a version that does this. In regards to number **2**, though, this app is made with [electron](http://electron.atom.io/), and as far as I know there isn’t a way to have a custom AppleScript dictionary for an app built with it, so I can’t add it.
