### ISSUE TITLE
Error at app launch

### ISSUE THREAD

**Issue by alextechtai** [vitorgalvao/fog#12]
![Screen Shot 2019-06-07 at 2 27 28 AM](https://user-images.githubusercontent.com/16980940/59094823-dbddde00-88cb-11e9-84d1-343c2eab29dc.png)

**Comment by vitorgalvao** [comment]
Thank you for the bug report, but you’ve given me no information with which to debug it.

Think about it: if you only post “I have this error”, what more can I say than “I don’t” and close the issue?

What’s your macOS version? What’s your Fog version? Where have you downloaded it from? Were you using it successfully before and it started erroring out, or is it your first launch? Are you running the packaged app, or trying to develop on it? I need details to be able to help you.

**Comment by alextechtai** [comment]
@vitorgalvao Sorry the background of the app is similar to the one mentioned https://github.com/vitorgalvao/fog/issues/13#issuecomment-500152830

**Comment by vitorgalvao** [comment]
https://github.com/vitorgalvao/fog/issues/13#issuecomment-500154234
