### ISSUE TITLE
Unable to authenticate Overcast.fm Account

### ISSUE THREAD

**Issue by davidgalloway** [vitorgalvao/fog#3]
Hello, I just downloaded Fog 1.1.0 and installed from the zip file. The app is asking me to authenticate my Overcast.fm account credentials. I enter my username and password, and click on the "Log In" button. The "Log In" button briefly changes colors when clicked, but nothing else happens. It also appears that none of the other buttons work but the text search window will successfully search for new podcasts, but if I try to click on one of those podcasts, nothing happens. 

https://www.dropbox.com/s/l001j75g69gd0fg/Screenshot%202016-04-12%2011.18.52.png?dl=0

Any suggestions? Thanks for working on this!

**Comment by vitorgalvao** [comment]
Can’t reproduce on a clean VM.

What’s your OS X version?

If you go now to overcast’s website, [log out and log in again](https://www.youtube.com/watch?v=kb2gzteVNa4), does everything work? Please try it in Chrome (to be closer to Electron).

**Comment by davidgalloway** [comment]
Vitor,

OS X is El Capitan 10.11.3 (15D21)

I logged out/in on Overcast.fm in Chrome. Fog is working now. I did that
earlier in Safari, but it had no effect.

Power cycling for the win, yet again! I still have no idea why the buttons
were unresponsive previously.

Thanks!

**Comment by vitorgalvao** [comment]
Oh well, all that matters is it’s working. Hope you enjoy the app.
