### ISSUE TITLE
v1.3.0 window too small double scroll bar

### ISSUE THREAD

**Issue by joevo2** [vitorgalvao/fog#6]
![screen shot 2017-09-30 at 3 40 17 pm](https://user-images.githubusercontent.com/697155/31043844-ad8fcbea-a5f5-11e7-85a4-8c70c6e9df54.png)
maybe a min width / height would fix it LOL

**Comment by vitorgalvao** [comment]
It already has a minimum width and height. Make the window bigger and the scroll bar will disappear.

I’ll change the minimum to be the same as the default.

**Comment by vitorgalvao** [comment]
Done in `1.3.1`.

**Comment by joevo2** [comment]
Awesome! 👍
